apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: microservices
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/bechor25/ms_test.git
        revision: main
        directories:
          # ← כל תיקייה טופ־לבל בריפו (HelloApi, Payments …)
          - path: "*"
            exclude: |
              clusters/**
              */k8s/**                 # אל תיכנס לתת-תיקיות k8s
  template:
    metadata:
      name: "{{path.basename}}"        # HelloApi, Payments …
    spec:
      project: default
      source:
        repoURL: https://github.com/bechor25/ms_test.git
        targetRevision: main
        path: "{{path}}/k8s"           # HelloApi/k8s
      destination:
        server: https://kubernetes.default.svc
        namespace: apps
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true       # יוצרת את apps אם לא קיים
