apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: microservices
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/bechor25/ms_test.git
        revision: main
        directories:
          # תיקיות-שירות ברמת שורש
          - path: "*"

          # התיקייה k8s עצמה (כדי שלא ייווצר כ־App בשם k8s)
          - path: "*/k8s"
            exclude: true

          # אם יש clusters/ לשימוש אחר – לא לכלול
          - path: "clusters/**"
            exclude: true
  template:
    metadata:
      name: "{{path.basename}}"        # שם האפליקציה = שם התיקייה (HelloApi)
    spec:
      project: default
      source:
        repoURL: https://github.com/bechor25/ms_test.git
        targetRevision: main
        path: "{{path}}/k8s"           # HelloApi/k8s
      destination:
        server: https://kubernetes.default.svc
        namespace: apps
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
