apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-api
  labels: { app: hello-api }
spec:
  replicas: 2
  selector:
    matchLabels: { app: hello-api }
  template:
    metadata:
      labels: { app: hello-api }
    spec:
      containers:
        - name: api
          image: bechor/hello-api:v1
          ports:
            - containerPort: 8080
