apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: microservices
  namespace: argocd            # ApplicationSet חייב לחיות ב-argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/bechor25/ms_test.git
        revision: main
        directories:
          # כל תת-תיקייה בריפו שיש בה k8s/ – לדוגמה HelloApi/k8s
          - path: "apps/k8s"
            
  template:
    metadata:
      name: "{{path.basename}}"             # שם האפליקציה = שם התיקייה (HelloApi)
    spec:
      project: default
      source:
        repoURL: https://github.com/bechor25/ms_test.git
        targetRevision: main
        path: "apps/k8s"                # <folder>/k8s מניפסטים
      destination:
        server: https://kubernetes.default.svc
        namespace: apps                     # ייווצר במידת הצורך
      syncPolicy:
        automated:
          prune: true                       # הסר משאבים שהוסרו בגיט
          selfHeal: true                    # שחזר משאבים שנמחקו ידנית
        syncOptions:
          - CreateNamespace=true            # צור את apps אם לא קיים