apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: microservices
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
      - list:
          elements:
          - cluster: eksmgmt
            url: https://kubernetes.default.svc
      - git:
          repoURL: https://github.com/bechor25/ms_test.git
          revision: main
          directories:
          - path: 'apps/*'
  template:      
    metadata:
      name: '{{index .path.segments 1}}-{{.cluster}}'
    spec:
      project: '{{.cluster}}'
      source:
        repoURL: https://github.com/bechor25/ms_test.git
        targetRevision: main
        path: '{{.path.path}}'      
        helm:
          releaseName: '{{index .path.segments 1}}'
      destination:
        server: '{{.url}}'
        namespace: '{{index .path.segments 1}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true  
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
